### ISSUE TITLE
Gestures option right / left backwards

### ISSUE THREAD

**Issue by oneofmanyacdcfans** [F4uzan/HgLauncher#18] opened 2019-03-08 18:37 UTC
In the settings menu for the gesture control, the swipe left and swipe right gestures are mismatched. I.e., if I set something to open on swipe left, it opens when I swipe right, and vice versa.

**Comment by F4uzan** [comment] 2019-03-08 21:52
This mostly isn't caused by anything but semantics. A similar issue was opened a while back (#8), so I feel the need to clarify that is clear.

That being said, to me either way will confuse a group of people. Maybe a better naming is needed instead? The current name is correct as far as my English knowledge goes; for instance, 'right swipe' is often treated as 'swipe to the right' (and vice versa).

I'll keep this issue open as a means of discussion.

**Comment by oneofmanyacdcfans** [comment] 2019-03-09 17:18
You're right, I did not think of that. To me, swipe left means to swipe FROM the left but to someone else it could mean to swipe left from the right!

I think a new name is a good idea. You could change them to say "Swipe from the left" and "Swipe from the right." I think that would clear up any confusion. 

On March 8, 2019 4:52:37 PM EST, F4 <notifications@github.com> wrote:
>This mostly isn't caused by anything but semantics. A similar issue was
>opened a while back (#8), so I feel the need to clarify that is clear.
>
>That being said, to me either way will confuse a group of people. Maybe
>a better naming is needed instead? The current name is correct as far
>as my English knowledge goes; for instance, 'right swipe' is often
>treated as 'swipe to the right' (and vice versa).
>
>I'll keep this issue open as a means of discussion.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/F4uzan/HgLauncher/issues/18#issuecomment-471088546

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by F4uzan** [comment] 2019-03-09 17:40
Definitely! I'm torn for the names though. We'll need a concise label for it; the name should take few space to conserve the current brevity.

**Comment by oneofmanyacdcfans** [comment] 2019-03-09 17:47
Do you think everyone would understand if it was "Swipe L to R" and "Swipe R to L" ?

On March 9, 2019 12:40:47 PM EST, F4 <notifications@github.com> wrote:
>Definitely! I'm torn for the names though. We'll need a concise label
>for it; the name should take few space to conserve the current brevity.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/F4uzan/HgLauncher/issues/18#issuecomment-471204672

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by F4uzan** [comment] 2019-03-09 18:12
They sound sort of redundant, but they do convey the message a lot better. I'll be looking more into the naming side of things, but for now, I'm happy to report that there will be nothing to fix code-wise.

**Comment by esmoak** [comment] 2019-03-12 01:06
Maybe "Swipe --->"

Like just use a directional arrow?

**Comment by oneofmanyacdcfans** [comment] 2019-03-12 01:07
Brilliant!

On March 11, 2019 9:06:55 PM EDT, esmoak <notifications@github.com> wrote:
>Maybe "Swipe --->"
>
>Like just use a directional arrow?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/F4uzan/HgLauncher/issues/18#issuecomment-471804468

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by F4uzan** [comment] 2019-03-12 07:21
I think the directional arrow is a nice compromise. I suppose the arrow points to where the user needs to swipe? (`->` would mean, for instance, a 'swipe to the right' action)

**Comment by sherlockbeard** [comment] 2019-04-07 20:50
@F4uzan can i send a pull request regarding to this issue?.

**Comment by F4uzan** [comment] 2019-04-08 05:08
You're welcome to introduce a PR for the issue. Though I'd like to say that this is more of a string issue than code, but feel free if you feel like you have a neat solution for it!

**Comment by F4uzan** [comment] 2020-10-30 11:27
The changes to strings should invalidate this issue (we're now using arrows to indicate the direction of swipes). I'll be closing this issue for now.

**Closed by F4uzan** 2020-10-30 11:27 UTC
