### ISSUE TITLE
Shorthand doesn't get detected until you refresh

### ISSUE THREAD

**Issue by macdonaldster** [F4uzan/HgLauncher#41] opened 2019-05-25 05:32 UTC
When you add a Shorthand string to an app, it doesn't get used until you refresh (e.g. from the long press on home screen).

Steps to reproduce the behaviour:

1. Select an app, add shorthand
2. Try to search for shorthand text
3. You will not find the app

Expected behaviour: when you search immeadiately after adding shorthand you should see the app.

**Comment by macdonaldster** [comment] 2019-05-25 05:32
I can try to fix this :)

**Comment by F4uzan** [comment] 2019-05-25 07:01
I can confirm this does happen on my side as well — though I can only reproduce it by searching for an app, adding a shorthand, then clearing the search query.

I welcome a PR for it. We can pile this up for v1.4.2.2, which should be due some time soon.

**Comment by macdonaldster** [comment] 2019-05-25 16:43
OK, I would like to get to this ASAP but not sure if time, will if possible! Same for #42

**Comment by macdonaldster** [comment] 2019-06-07 02:03
Cautiously optimistic I have a fix for this bug. Going to need to do some testing. Took a while to figure out how to right click on action_* and see where it was handled in code then I was able to dig in quickly. Starting to like Android Studio a bit more as well.

**Comment by F4uzan** [comment] 2019-06-07 13:01
That's nice to hear! I'm currently stuck with real life at the moment, and I haven't been able to consistently find the time to work on the issues around — so, the launcher hasn't been receiving much activity on my end. I'll try opening up some time later this week to see if I can lend a hand at fixing this.

**Comment by macdonaldster** [comment] 2019-06-07 21:04
I think I've got it, was just providing an update. I, too, and "time constrained". Hopefully, I can get this tested and submit a PR this weekend. If I can fix a couple bugs would you prefer one PR per bug? (no promises but you never know)

**Comment by F4uzan** [comment] 2019-06-07 22:28
If they are related enough, coupling them would actually be better — but I wouldn't mind them split too. As for this and #42, we can have them in one PR as they seem to crawl from one source of problem.

**Comment by F4uzan** [comment] 2019-06-11 07:36
I have pushed a commit that addresses this and #42. You may want to see if the commit properly sorts out the issue at hand before we close this.

**Comment by macdonaldster** [comment] 2019-06-11 10:52
Thanks, I will check it out! It looks more elegant than the sledgehammer I used - just rebuilt the entire app menu after the shorthand edit was done. Live and learn. :)

**Comment by F4uzan** [comment] 2019-06-11 12:46
I had a similar idea before as well (recreating list and such). It took me one long stare to realise the simplest solution available.

Once we get this closed, I'll set sail for v1.4.2.2 as this seems to be a lingering issue since I have introduced shorthands (and I much rather have it fixed in a more manageable release than, say, v1.4.3 where I expect bigger changes to happen).

**Comment by F4uzan** [comment] 2019-08-16 17:37
As this has been covered in v1.4.2.2, I'll be closing it. Please reopen should there be more issues related to it.

**Closed by F4uzan** 2019-08-16 17:37 UTC
