### ISSUE TITLE
App dosen't hide when hiding from list

### ISSUE THREAD

**Issue by Shadowspear123** [F4uzan/HgLauncher#57] opened 2020-01-21 03:24 UTC
**What's the issue?**
When hiding an app from long press options in app list, the app reappears on the next launch of app list.

**To reproduce…**
Steps to reproduce the behaviour:
1. Launch app list
2. Long-press an app
3. Tap actions, then tap hide

**Expected behaviour**
App should hide and then *stay* hidden even in later launches of app list.

**What did you see instead?**
The next time the app list is opened, the the "hidden" app is still showing.

**Device information:**
 - Device: Samsung Galaxy S8
 - OS: Android Oreo
 - Hg version:  Latest from F-droid
 - Are you running an official release from Play Store/GitHub Releases? Yes

**Comment by F4uzan** [comment] 2020-01-21 11:35
I can't seem to reproduce this issue. Are you able any other additional information regarding this? Can you see if the app is added to the 'Hidden app' list in the launcher's settings?

**Comment by Shadowspear123** [comment] 2020-01-21 13:01
The app dosen't get added to the hidden list.

**Comment by esotericDisciple** [comment] 2020-08-17 22:32
i have the same issue on s10+ (usa version)...could shelter/work profile be a cause?

**Comment by F4uzan** [comment] 2020-08-17 23:04
@esotericDisciple I don't think that is the case, but there have been plenty of fixes done regarding this issue. If it is possible, can you test the RC builds in Google Play Store and see if the issue still occurs?

**Comment by F4uzan** [comment] 2020-10-30 11:18
I'll be closing this issue as I'm unable to reproduce it any further in v1.5.0. Please reopen if you still encounter the issue.

**Closed by F4uzan** 2020-10-30 11:18 UTC
