### ISSUE TITLE
Request: Support auto-opening app list

### ISSUE THREAD

**Issue by zmingee** [F4uzan/HgLauncher#7] opened 2019-01-16 22:11 UTC
Again, thanks for all the work on this! I hope it's successful.

The only usability issue I have is the inability to auto-open the app list. I don't use widgets, and use a black wallpaper for my AMOLED display. I'd love an option to avoid the extra tap.

Also, I'm new to Android Pie/9, but I've seen a couple launchers that support the new "gesture navigation" controls to get to the app drawer. That would be a cool feature to have here too if it's something simple.

**Comment by F4uzan** [comment] 2019-01-17 06:14
I suppose the auto-open gets triggered whenever the user (re)enters the launcher — so as to keep it always open (and closed by the action of the user)?

**Comment by ranfdev** [comment] 2019-01-17 17:09
Thank you for your awesome work!
It's cool, but I think you should add a "persistent app list" feature, to skip the wallpaper page.

**Comment by zmingee** [comment] 2019-01-20 01:33
I'd add a gif or something to show, but with my setup I have the amoled always on display, then a minimal lockscreen that's all black, and then an all black wallpaper. It's just a little odd to see more "content" on the always on display and lockscreen than the homescreen itself. I know, it's a small gripe. But it would be handy to have a "persistent list state" of some kind that's togglable.

**Comment by F4uzan** [comment] 2019-01-20 07:57
f9ab127 should be all-good for this, if I'm getting the description correctly. It keeps the panel open at all times whenever the user enters the launcher. Let me know if this is the intended behaviour or not.

**Comment by ranfdev** [comment] 2019-01-20 16:47
Yes, it is

**Comment by F4uzan** [comment] 2019-01-25 10:19
Closing this as the feature has been merged to the new release.

**Closed by F4uzan** 2019-01-25 10:19 UTC
Labels: enhancement
