### ISSUE TITLE
Search bar is still reappearing and not clickable

### ISSUE THREAD

**Issue by realrufans** [F4uzan/HgLauncher#33] opened 2019-05-01 18:15 UTC
#### Expected behavior

So I read this commit where you fixed [reappearing search bar under power saving mode](https://github.com/F4uzan/HgLauncher/commit/2a498811aa976994862becd139f9a602b5f452ca).
After downloading the latest version of the Launcher v1.4.2, I expected not to see the search bar.

#### Actual behavior

 I was able to see the search bar and it is not click able.  But, it's click able on V1.4.1.3

#### How to reproduce
- make use you're using the launcher (latest version), and you're on battery saving mode.
- tap on your home screen to access App list, then go back to home screen.
- the search bar will appear
- try clicking on it. (It won't respond)

- Version: Hglauncher 1.4.2 from release page.
- Operating system: Tecno Camon X pro ( Android 0)

<Hr>

#### Recording Of The Bug

![MNML-May1-07021-1556733846052.gif](https://cdn.steemitimages.com/DQmdVwQYqFstY1Xhy2Ju957Vv1UkET8zV9uMpA5r2pdK3uZ/MNML-May1-07021-1556733846052.gif)

**Comment by realrufans** [comment] 2019-05-01 18:29
Your code says 

```searchContainer.setVisibility(View.INVISIBLE)```

Shouldn't it 

```searchContainer.setVisibility(View.GONE)``` ?

That would hide the search bar from appearing

**Comment by F4uzan** [comment] 2019-05-01 18:59
I especially avoided the use of `View.GONE` because of the way the launcher works. Although it might be a minor performance hit, repeatedly setting the view to `GONE` will trigger layout changes — and for a use case where the search bar might be continually be shown or hidden, I'd rather not guess the performance impact.

For now, I'm able to successfully reproduce this on my side. I'll apply a fix soon, as I think I have a good grounds on what causes this. Thanks for the report!

**Comment by realrufans** [comment] 2019-05-01 19:04
Perfect 👍 
I love this project btw.  Thanks for Making it.

**Comment by F4uzan** [comment] 2019-05-03 09:19
This should be fixed in c5c6579e581e77fa28da85a15ef1abc0997e2a1f. Once again, thanks for the report!

**Closed by F4uzan** 2019-05-03 09:19 UTC
